apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis-operator.fullname" . }}
  namespace: {{ include "redis-operator.namespace" . }}
  labels:
    {{- include "redis-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
  {{- with .Values.extraAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      {{- include "redis-operator.selectorLabels" . | nindent 6 }}
      control-plane: controller-manager
  template:
    metadata:
      labels:
        {{- include "redis-operator.selectorLabels" . | nindent 8 }}
        control-plane: controller-manager
      {{- with .Values.extraAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.operator.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: manager
        image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
        imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
        command:
        - /manager
        args:
        - --leader-elect={{ .Values.operator.leaderElect }}
        - --health-probe-bind-address={{ .Values.operator.healthProbeBindAddress }}
        - --metrics-bind-address={{ .Values.operator.metricsBindAddress }}
        {{- with .Values.operator.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        {{- with .Values.operator.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      serviceAccountName: {{ include "redis-operator.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      {{- with .Values.operator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
