---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: redis-operator
  name: redis-operator-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  namespace: redis-operator-system
  labels:
    app.kubernetes.io/name: redis-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redis-operator-manager-role
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["cache.bubua12.com"]
  resources: ["redis"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["cache.bubua12.com"]
  resources: ["redis/finalizers"]
  verbs: ["update"]
- apiGroups: ["cache.bubua12.com"]
  resources: ["redis/status"]
  verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: redis-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redis-operator-manager-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: redis-operator-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: redis-operator-system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: redis-operator
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: redis-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
        app.kubernetes.io/name: redis-operator
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /manager
        args:
          - --leader-elect
          - --health-probe-bind-address=:8081
        image: bubua12/redis-operator:v0.0.1
        name: manager
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
